### PR TITLE
Add terminalutils

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add `prompt` module, 1 proc.
- This is the Nimble terminal "menu thingy" we are using everyday, adapted to work with stdlib.

So more than once been asked "How to import the Nimble menu thingy" or if its possible to do so,
so I tough lets make it happen, and stolen the code from Nimble, is the same code basically, 
code is already there anyways..., just making it more usable.

:)

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Do you prefer other module name?, like `tui` or something?, just in case some day something can be added to it.
:thinking:

File: src/fusion/tui.nim [hunk 1]
```diff
@@ -0,0 +1,65 @@
+## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
+##
+## .. code-block:: Nim
+##   echo promptInteractive("is Schrödinger's Cat alive?", ["maybe", "maybe", "maybe"])
```
Comment (timotheecour) [inline src/fusion/tui.nim:4]: * yes no maybe, otherwise not clear it works

File: src/fusion/tui.nim [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import terminal
+
+
+proc promptInteractive*(question: string, answers: openarray[string], width: Positive = 80): string =
```
Comment (timotheecour) [inline src/fusion/tui.nim:8]: can we make sure CI is hardened to fail here (because of openArray vs openarray), eg by adding `--styleCheck:on` to `test` nimble task ?

File: src/fusion/tui.nim [hunk 3]
```diff
@@ -0,0 +1,65 @@
+## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
```
Comment (timotheecour) [inline src/fusion/tui.nim:1]: tui is a bad name. termutils?

File: src/fusion/terminalutils.nim [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    setForegroundColor(fgDefault)
+    # Loop through the options
+    for i, arg in answers:
+      # Check if the option is the current
+      if i == current:
+        writeStyled("> " & arg & " <", {styleBright, styleUnderscore})
+      else:
+        writeStyled("  " & arg & "  ", {styleDim})
+      # Move the cursor back to the start
+      for s in 0..<(arg.len + 4): cursorBackward(stdout)
```
Comment (Yardanico) [inline src/fusion/terminalutils.nim:35]:
```suggestion
      stdout.cursorBackward(arg.len + 4)
```

File: src/fusion/terminalutils.nim [hunk 5]
```diff
@@ -0,0 +1,65 @@
+## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
+##
+## .. code-block:: Nim
+##   echo promptInteractive("is Schrödinger's Cat alive?", ["yes", "no", "maybe"])
+import terminal
+
+
+proc promptInteractive*(question: string, answers: openArray[string], width: Positive = 80): string =
+  ## Terminal prompt that asks a `question` and returns 1 answer from `answers`.
```
Comment (Yardanico) [inline src/fusion/terminalutils.nim:9]:
```suggestion
  ## Terminal prompt that asks a `question` and returns only one of the answers from possible `answers`.
```

File: src/fusion/terminalutils.nim [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+  # Adapted from Nimble source code to stdlib, adding width optional argument.
+  assert question.len > 0, "question must not be empty string"
```
Comment (Yardanico) [inline src/fusion/terminalutils.nim:11]:
```suggestion
  assert question.len > 0, "Question must not be empty"
```

**Review by Yardanico — COMMENTED** [review]
Some small corrections and simplifications (didn't test)

File: src/fusion/terminalutils.nim [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+      if i == current:
+        writeStyled("> " & arg & " <", {styleBright, styleUnderscore})
+      else:
+        writeStyled("  " & arg & "  ", {styleDim})
+      # Move the cursor back to the start
+      for s in 0..<(arg.len + 4): cursorBackward(stdout)
+      # Move down for the next item
+      cursorDown(stdout)
+    # Move the cursor back up to the start of the selection prompt
+    for i in 0..<answers.len: cursorUp(stdout)
```
Comment (Yardanico) [inline src/fusion/terminalutils.nim:39]:
```suggestion
    stdout.cursorUp(answers.len)
```

File: src/fusion/terminalutils.nim [hunk 8]
```diff
@@ -0,0 +1,65 @@
+## * Terminal prompt that asks a `question` and returns 1 answer from `answers`.
```
Comment (Yardanico) [inline src/fusion/terminalutils.nim:1]: Also maybe we should have a more generic top level documentation if this module is named "terminalutils"? And move prompt-specific info into it's own docs

**Comment by Yardanico** [comment]
This is the version with my small styling/functionality changes just for reference:
```nim
proc promptInteractive*(question: string, answers: openArray[string], width: Positive = 80): string =
  ## Terminal prompt that asks a `question` and returns only one of the answers from possible `answers`.
  ##
  ## .. code-block:: Nim
  ##   echo promptInteractive("is Schrödinger's Cat alive?", ["yes", "no", "maybe"])
  ##
  # Adapted from Nimble source code to stdlib, adding width optional argument.
  assert question.len > 0, "Question must not be empty"
  assert answers.len > 0, "There must be at least one possible answer"
  writeStyled(question, {styleBright})
  var
    current = 0
    selected = false
  # Incase the cursor is at the bottom of the terminal
  for arg in answers: stdout.write "\n"
  # Reset the cursor to the start of the selection prompt
  cursorUp(stdout, answers.len)
  cursorForward(stdout, width)
  hideCursor(stdout)

  # The selection loop
  while not selected:
    setForegroundColor(fgDefault)
    # Loop through the options
    for i, arg in answers:
      # Check if the option is the current
      if i == current:
        writeStyled("> " & arg & " <", {styleBright, styleUnderscore})
      else:
        writeStyled("  " & arg & "  ", {styleDim})
      # Move the cursor back to the start
      cursorBackward(stdout, arg.len + 4)
      # Move down for the next item
      cursorDown(stdout)
    # Move the cursor back up to the start of the selection prompt
    cursorUp(stdout, answers.len)
    resetAttributes(stdout)

    # Ensure that the screen is updated before input
    flushFile(stdout)
    # Begin key input
    while true:
      case getch():
      of '\t', '\x1B':
        current = (current + 1) mod answers.len
        break
      of '\r', ' ':
        selected = true
        break
      of '\3':
        showCursor(stdout)
        raise newException(OSError, "Keyboard interrupt")
      else: discard

  # Erase all lines of the selection
  for i in 0 ..< answers.len:
    eraseLine(stdout)
    cursorDown(stdout)
  # Move the cursor back up to the initial selection line
  cursorUp(stdout, answers.len)
  showCursor(stdout)
  result = answers[current]
```

I've found some problems with the implementation:
1) Default width is IMO too high, it should probably be calculated as a width of the longest answer + length of the question + 2
2) Maybe it's better to put possible answers on the next line? Then we'll have less width usage since the question could be long, but the answers will be short

**Comment by timotheecour** [comment]
can this be customized to use a horizontal vs vertical layout?

**Comment by Yardanico** [comment]
@timotheecour you mean questions on a single line vs questions on separate lines?

**Comment by timotheecour** [comment]
no I mean answers layout

File: src/fusion/terminalutils.nim [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+        showCursor(stdout)
+        raise newException(OSError, "Keyboard interrupt")
+      else: discard
+
+  # Erase all lines of the selection
+  for i in 0..<answers.len:
+    eraseLine(stdout)
+    cursorDown(stdout)
+  # Move the cursor back up to the initial selection line
+  for i in 0..<answers.len: cursorUp(stdout)
```
[the remark this answers is not in the document]
Comment (juancarlospaco) [reply src/fusion/terminalutils.nim]: Thanks for the contribution, but all the suggestions are on the latest commit together.

File: src/fusion/terminalutils.nim (hunk 4 above)
Comment (juancarlospaco) [reply src/fusion/terminalutils.nim]: Thanks for the contribution, but all the suggestions are on the latest commit together.

File: src/fusion/terminalutils.nim (hunk 7 above)
Comment (juancarlospaco) [reply src/fusion/terminalutils.nim]: Thanks for the contribution, but all the suggestions are on the latest commit together.

File: src/fusion/tui.nim (hunk 2 above)
Comment (juancarlospaco) [reply src/fusion/tui.nim]: Out of scope for this PR, but I like the idea.

File: src/fusion/terminalutils.nim [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+
+
+proc promptInteractive*(question: string; answers: openArray[string]; width: Positive; indicators = ['>', '<']): string =
+  ## Terminal prompt that asks a `question` and returns only one of the answers from possible `answers`.
+  ##
+  ## .. code-block:: Nim
+  ##   echo promptInteractive("Is Schrödinger's Cat alive?", ["yes", "no", "maybe"], 40, ['>', '-'])
+  ##
+  # Adapted from Nimble source code to stdlib, adding width argument.
+  assert question.len > 0, "Question must not be empty"
```
Comment (timotheecour) [inline src/fusion/terminalutils.nim:15]: I know https://github.com/nim-lang/RFCs/issues/266 is still in RFC mode, but this should use `enforce`, it's a recoverable exception and validates user input, not internal logic that should crash the application.

**Comment by TensorTom** [comment]
Was mentioned [here](https://forum.nim-lang.org/t/6965#43620).

**Review by alaviss — CHANGES_REQUESTED** [review]
Since this was ripped off nimble code, please insert the corresponding copyright and license for the file.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2

The license from https://github.com/nim-lang/nimble/blob/master/license.txt should be inlined into this file header and not `license.txt` as fusion is not dual-licensed.

File: src/fusion/terminalutils.nim [hunk 11]
```diff
@@ -1,5 +1,37 @@
 ## * Utilities and convenience procs built on top of `terminal` module.
```
Comment (timotheecour) [inline src/fusion/terminalutils.nim:1]: * add `Adapted from: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2` so we can trace it back to its origin (say in case a refactor between the 2 is later done, or bugfixes are done in either)
* @alaviss just wondering if it's ok to have a license file as here; a package that imports (recursively) terminalutils may not be aware that one of its dependencies is subject to this license?

File: src/fusion/terminalutils.nim [hunk 12]
```diff
@@ -0,0 +1,99 @@
+## * Utilities and convenience procs built on top of `terminal` module.
+##
+## License
+## =======
+##
+## `promptInteractive` code is based and adapted from
+## `Nimble source code <https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim#L1-L2>`_
```
Comment (alaviss) [inline src/fusion/terminalutils.nim:7]:
```suggestion
## `Nimble source code <https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim>`_
```

File: src/fusion/terminalutils.nim (hunk 11 above)
Comment (alaviss) [reply src/fusion/terminalutils.nim:1]: > @alaviss just wondering if it's ok to have a license file as here; a package that imports (recursively) terminalutils may not be aware that one of its dependencies is subject to this license?

It should be fine, BSD 3-clause is compatible with MIT AFAIK. Also the mix-and-match of licenses within a project is not unusual and people who have strict legality requirements must subject themselves to audit every single dependency used.

**Comment by juancarlospaco** [comment]
Ready to merge.

**Comment by timotheecour** [comment]
@juancarlospaco can you assign the review to @dom96 instead because of the code history?

**Comment by juancarlospaco** [comment]
@timotheecour 
I do not have permission to do it.

**Comment by timotheecour** [comment]
done

**Comment by dom96** [comment]
> So more than once been asked "How to import the Nimble menu thingy" or if its possible to do so,
so I tough lets make it happen, and stolen the code from Nimble, is the same code basically,
code is already there anyways..., just making it more usable.

There is a reason the Nimble code is available as a library, why not just use it?

**Comment by nc-x** [comment]
Firstly, I would like to say that i am one of the few people who still do not understand the reasoning behind fusion, and the criteria by which a module is supposed to be put into stdlib, or fusion, or a separate nimble package.
  
Personally, I would have preferred no fusion, and some of the modules from here should have been in stdlib and some as separate nimble packages, so I won't comment on whether we need this terminalutils in fusion or not.

However,
> There is a reason the Nimble code is available as a library, why not just use it?

(I don't know how much code is included in the nimble as a library, so i may be wrong but anyways...)
  
Because nimble is not a tui library? And if I need simple tui utilities I would prefer importing a simple stdlib module, or a tui library from nimble, and not import a fullblown package manager just to use 5% of its functionality, especially considering the fact that the functionality I want to use has nothing to do with package management?

**Comment by dom96** [comment]
@nc-x nothing stops you from just importing the ``cli`` module from Nimble. Just ``import nimblepkg/cli`` and you can use it. It's a pretty lightweight module: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/cli.nim

**Comment by nc-x** [comment]
Is the cli module a separate nimble package, or does it come inside the nimble package?

the download size of nimble won't be particularly big, but still (atleast to me) it doesn't feel right to add dependency to nimble.

In any case, we also need to take into account the discoverability of nimble as a tui library. Even if nimble directory shows nimble when searching for tui library, most people are going to ignore it thinking that maybe it is tagged wrong because nimble is a package manager not tui library.

**Comment by timotheecour** [comment]
> it doesn't feel right to add dependency to nimble for using tui utilities

I agree. And even though nimble is, well, a package, manager, it would still be possible for it to have a `require tui` optional dependency (not sure if feasible at the moment, but it's doable). Libraries grow and having a dedicated `tui` package makes more sense than having to rely on nimble, as it'd quickly enter a friction mode (separation of concerns: nimble shouldn't focus on full blown tui). So I support having `tui` separately from nimble instead of requiring a dependency on nimble.


> one of the few people who still do not understand the reasoning behind fusion, and the criteria by which a module is supposed to be put into stdlib, or fusion, or a separate nimble package

you are not alone; for me it's still very much an experiment, and some downsides are as follows:
* requiring it to work with nim all the way down to 1.0.x may add too much friction
* slower development pace compared to individual nimble package; in particular, the fact there's no "staging period" (combined with lack of semver, refs https://github.com/nim-lang/fusion/issues/30) is a flaw; it means you can't have trial/error phase that is essential for maturing libraries, especially in between point releases
* the fact that fusion is be bundled with nim (even copied into std during install) means you'll end up with duplicate fusion imports: one from the bundled fusion, and one from pkg/fusion; this in particular will lead to duplicate symbol link errors as soon as you have some exportc symbols defined; see the whole thread here: https://github.com/nim-lang/fusion/issues/25#issuecomment-708099682 that worries me a lot

on the flip side, the positive aspects about fusion would be:
* community maintained (no package-gone-rogue/unmaintained)
* batteries included extended standard library, where things work well together
* common infrastructure to reduce overhead (testing/docs/etc) + more visibility

**Comment by dom96** [comment]
> Is the cli module a separate nimble package, or does it come inside the nimble package?

Yeah, it's part of the `nimble` package. To be fair, now that Nimble supports multiple packages in the same repo, exposing the ``cli`` module as another package should be very trivial. I would prefer to see that as a PR rather than this :)
